---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 23.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    metrics:
      main:
        enabled: false
    workload:
      exportarr:
        enabled: false       
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        hosts:
          - host: radarr.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - radarr.${BASE_DOMAIN}
            clusterIssuer: cluster-cert
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/bigdata/plex
        mountPath: /plex
        server: 192.168.68.109