apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9CXR8QO6RIev7+jgtzsRLUabJtamJq7YceJDvuLF23Q8u8ON1ZuJs7gSjn2tUnkk290b1LXCOViboZDHXiVV5FQ=,iv:NyleImGJuHdznRIkqiwJrGGWx+1et0EnrFdUFRuW8Wo=,tag:kZDTBYRcD9KsYfBBMzCdYw==,type:comment]
    #ENC[AES256_GCM,data:MDzMUcn4iNVb51TEXFC+2tTz2sveS5CZvye0W25NYIz6XLjtJXKPKeg34Oo=,iv:LK+U1HpEvG3cxsJslFjqmpklCP/zsgKOphgn8gmeaK4=,tag:o0CdQWb9G5JxettDsBF5Iw==,type:comment]
    VIP: ENC[AES256_GCM,data:+A4nK/oymFWgYZX5Dg==,iv:vyN5ET/xZDXdTxucOsb94aZRfsRTgQl3LU43hq4ZplQ=,tag:IeHV/FmjKB8iQfrq3twMpw==,type:str]
    #ENC[AES256_GCM,data:Q31gMeVIdzC/sDWWd0HryJif6DQwPJ8gFZo=,iv:XmqiiZa/FbzIjet2pe+xoFwozNEXXlU/qv5WkMEwFto=,tag:aVGUyg+0wwx1FBNB5J/6tQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:XcGj0hfM4KqoNuUvQJ8=,iv:ZSFmnnojEtCNiHa95WRj46YKEKKBGVrelQqigatGcss=,tag:hnd7QG2EkjdUwhLbzR/fyg==,type:str]
    #ENC[AES256_GCM,data:5us+AdyA3YVjaAWbHy4F6Des5O6vyuvsHX2g2by1Kl7vVQ==,iv:xAcdVZWzCDFSI5ByKsKDe4uHzwvyTbCrqJdKRdwunts=,tag:7AXKuNXmCP6B3S1pu9Wx3A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:4bpMZF5zZA9onzq+,iv:8ooA9WM2NURLQFrZBOkRFwi5tS9FGdnZgIom8fQwadI=,tag:bGa476xrPc1YupLvXYh95w==,type:str]
    #ENC[AES256_GCM,data:LM5acGv0EyLY2xZBZfhksDRyYuoEaIgH9IbQY9+r1wMra3GTNsfj0EcVWJW4wAs=,iv:uTBKYMBxUTAOJHQkoUj1g7UsNVN9xmmYjKOgbqEWxxk=,tag:2A+f2jn5eerZjF0JucAl0A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:saIplZHdzolznV/UmHtJuCNPBHnArxDgNHsJ,iv:rjpJPYa0tmYg5G0EFzJmAUST1biA1YzdknlGpcy5u5U=,tag:9Zlry8AbpAxzGenpOB1+/Q==,type:str]
    #ENC[AES256_GCM,data:HUMU+ZO+a2c8pTOUg5jFhYQlkGV5L0zSrlJj3v8AKAz4rsH28TP2US0VHIFvhNX8U4YKjzctscSahvRJhmXdJK5sZh348ZkL/cyoO7Mlc0Y=,iv:nWRCZNwX30ukmMzskMSAQNcPBCLOcnchZ6Sl81LvdEM=,tag:d+1GmDkhsRBsFKW/k2N35Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jDsSWU2AZGUaX4O+yQ==,iv:LmblC4/WNkGqWzBF9tjVuw/b60icAzObAUOz/QxGss4=,tag:3+VICsbqr7CEsB2lMZLOFQ==,type:str]
    #ENC[AES256_GCM,data:5orhPqO6GWDOXZXZzvUJca+h2psCOwG7fDpUjQMotC9CLfOspX0COlefRC53Da/sJuQiu7WB314Hpap58KVWgJMffcQ=,iv:O6dT6HYNm3poV49lphBDr+JVUkCaUv+p032KhFjkAaY=,tag:DdQEWQ7ARhqGcBjCHjevEw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:KKYRRC99GDbuP4/l5Q==,iv:nTYXk3TSgSsLwggRg6hMP97c+AoOl+/fNey/iIrWqRI=,tag:2tZyCtNEdtwCiuSYljeedA==,type:str]
    #ENC[AES256_GCM,data:n4cyH5UHRr+tKZ05JQzGHaBZIcPKQF0bYZjY4c19inB4fMNopN6j9svVLK/yg9wIXtpxDHzSiMw=,iv:l2OJ69Ef8Cv1NWdOFZkLWJZpuwIEugSrXEvcrxnppZ8=,tag:00XERQyWBTWZ/6nEOy8dJg==,type:comment]
    #ENC[AES256_GCM,data:l4z8ODlChmsFK1JlEsAwn1cpj9NO/Cwlfw==,iv:rC8tbhI+FCEy8FhVCW870cifPs62NLh4ojnVdSIQs8w=,tag:qVm4K3YrhuZt9k1g8Ns1lA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:DPHSJh79epmEXUaUsmpk/32qlxzDc5p9ID7QAm7Fa6VgJmNudcbgZiXJ1Q==,iv:VUyNGaDpLommeJuTyuX0vrOT+4wn8Ev0Qsr0NPXCh4I=,tag:AXNYEJRb7BDscYE7BinDZQ==,type:str]
    #ENC[AES256_GCM,data:XaphgQR/7SxIPIL5rw==,iv:1zzfFP8qOOGmUNzy+T2HYq1EnPpw8o24lZReB7PxuZQ=,tag:AhKFIH/Sp3OXpgpqsMF1AA==,type:comment]
    PODNET: ENC[AES256_GCM,data:Iwbt797vz41R5Ln5ZQ==,iv:XxWFOxIy1C0mD6zvVAAVKauGzCh80VxlrBoFsWsH1R4=,tag:tmqCD4uWi995Oy36CZ4VHQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:oyLWQfUm/Btq8ONLdw==,iv:sqkCKs2oEA41ZtsZ8A6sk7ow0uCQQzHevWPCRf5lBEw=,tag:vfbaxAoMvymKiEvZC5NaGw==,type:str]
    #ENC[AES256_GCM,data:VbXTFjgwRPA3xQ==,iv:Up0YhI4tumJG/lSdeZjTmwM48x/y35ma4kfKKmAFytM=,tag:+9UXnDZKy1rHCJrqBSm+cQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:vhZN4scJUdOrH0qs1g==,iv:bL//CfeqE1AY4aUPiSRE4/GKhejy4D58GhHn9ytxbyI=,tag:KE8uIB7Uc08HkwwytHxnzQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:xQTNGRlYCpvF6QEV2A==,iv:zzeUo4CwRl0aH9pPbMAkwLbAmXM4Hi1meP+ZebGleo0=,tag:TpEOiwTLTrqiysQUXgZU5g==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:DBOXDP3tOv7ZNOmTr0U=,iv:pIxdFdi71Pubbd9tGbQEgol96G8BgOCgnpLiLjDN/TQ=,tag:kMcicoTfW94TpJsym34RCg==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:5n/eo2A8DRuJq7MkIzo=,iv:VWDz+YVK5TH6BmK9tcAZzyZ87VEcbYQEB8Xkur3y9ls=,tag:b3kBtqY7TWwq+gVLUQ8AFw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:q32yOp507fMMNOlfAfw=,iv:0i7IdAZFCIw/31vs56AkaWOthNLo2FHNGHPKBxj3H+g=,tag:GiVz4wba4KLDUfDgAZuRKQ==,type:str]
    HA_IP: ENC[AES256_GCM,data:BbqgO+cG9FP53U9TYbU=,iv:hgtfwhD56NP4F4k14XXcW5bFaSQVF8ZLklZ9XqU2JAM=,tag:dxt0kQdjMxGxfdprQiX5mQ==,type:str]
    MC_IP: ENC[AES256_GCM,data:1CVSsowFYCAy5hPwp4c=,iv:DvqtXvinwiW5F12JDN4ErZKZsIGrqbsA2Bs9VJXdEqI=,tag:PriV0yA4fAa0veRIZVFncQ==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:4sDznN95kw7F1j/kdqk=,iv:ekYDPMCLlHXyKr0zNwQFOkG7g9aMAx3epm6UUkT9jfM=,tag:R2nWLs6niwqUlZWSHEaYkA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:WoAndf84uZDj1SN5bAuvMKVL+r4iVaG6Y1wAl9OCKtNfFRL50cgkiQ==,iv:SdJWIltUsH/yslkAtmMXpbjHtjmzZWo1ZL4juzVwAkk=,tag:PMsbb+QmgGJ3vtucrgWLUg==,type:str]
    EMAIL: ENC[AES256_GCM,data:3pHMxdlPbU/g0RGaZwMROuarglrKwOdjtIOvIFXyzw==,iv:zYrJ4piXpmXHdaRmhWzpcdafG6YFW3w7QVoaiJPNRj4=,tag:O97U2JY0Go5oos9sCOvaTw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Uo0rd0nxD4Ram1MWOg==,iv:zAtI2ICavGUbVAiqoTtw9TV8/4iXKR0LmYSVt/Z0zr8=,tag:co2bjcIKgE+sW4bwWsLTfA==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:tFKCFHbCMB6tL147nCFttlYPHJLyTp8=,iv:ZFUYpAaG6Alaqql1xD4Z3UY4SdVNQExVT61gVTamDjE=,tag:3bwTg4i6fsFUaVgEFscymg==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:8iR79LLJL0o9zRkgSfWIeo4ceKMm53CWciE=,iv:stC1zBXXivYC4LKT+XqisuHCSOsxEyb4Aa2pohlmhY4=,tag:FTvmfptiAD+qDAyvf9Rz1A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:3LgOqg==,iv:I7Fru7DEPoe2a0n5M23/pl+JfMddAsQgnNIJFrGKCdM=,tag:ZXxzCrSaf/JQVhCVMkDjbQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15r0fc8muy2t2wvyz7lxdrgk9us8jjnvs3evj7ju24zc6w7xavqas9q749m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MURMTVJiaWk4YnB2aTda
            S2gwUGNpV2h2SzFYcHM0VEhaWlpsR0ZnZ2dzCmlEMlhFQUtuOGF4Ry9pM0NISjYx
            Wk4vaHNyS3FCdzJiUHVvc3VXN0NiaWMKLS0tIHNoSi9QTzNhcjMzcUxBa0ZHNWlR
            cFZNL05MSVdFSCtPOTAycVpRa3BVaTAKNpUgtI40NtDuhA3XZ1JisCrzpKYetOQX
            cTXuoPip+BM2F1I3e8/L+Eem51m8UIcOhswL+Jx40DjtHpzwHGqmhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:25:48Z"
    mac: ENC[AES256_GCM,data:QwDyApnHc/Y1kUsU9RqittlXCuWxb4uCcNCJrVtOP8G5W1fn4nZqZLj9c4+i1Lr/sHj23QISi+8a7nw2komQgCK0fltogZ6TJlkEjXUaB9KL+knImDNpq3MUM/8fSc9YDBkwfK/YpaiRlhHjm41VxSxvCE+2rUhbT5gRflRKdQ4=,iv:GO95tBy3k0Ljp/UcnaEk7WuiAxi26lGJ+hKIR/ab0Ts=,tag:1veDoyvg1aFuDi5equ5Mjg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
