apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Gh51uUCaPMNK1t1wOPRf/6f3QdiIeGZRfv6s9xofWjJTHWIPEsio+K84vOqDy8Jv8cWYV05+nFMduOQ+GIiK5P8=,iv:eYSEfcJtkFoeShA1bKbmX+XKxGarJJqJ6Nv8P8fzCWc=,tag:Xo5Aa4RcrPThkRNf90o6Zg==,type:comment]
    #ENC[AES256_GCM,data:KOy73x+kaacr9wOEXd/2QJavd+0Cx+acvu4tkf2umAs9Vqd82GbHD+LuJ+s=,iv:imnJo/4kjCOcv33Bjm+Uwi8sk3iApSpLaBCbfHwlvOk=,tag:BEL5lyXvo3x6me3Hkm+n+A==,type:comment]
    VIP: ENC[AES256_GCM,data:RwRKmf1cwdISIJGhPw==,iv:gbwW69X8tf2mtVZMN3zZii4sSeT+VKOt1sq6aM2+SwU=,tag:0GVvBouCXe6U1cBPlsD6IA==,type:str]
    #ENC[AES256_GCM,data:Td0IDB0gCD4G1fneZkg/2NgtjoMfR32/X7A=,iv:wAJ3HcVXzHEePf3stDzsMOA1AxPp0q3q/aMIJRTttSo=,tag:fyjARoU0A4/3Rss5+8LuRQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:PNuMzS36k8Nh1lhiJWs=,iv:pU2B8NUfqhiVcW67Yz8qzHKtqRy424U1obqlp+07JKc=,tag:IBdEcavpLvNBFN/2xusHaQ==,type:str]
    #ENC[AES256_GCM,data:E4/vAqO5aegRjBrZtZCm1wN1yGZqcnR8Jgo4wkNBUg1qbA==,iv:8KPppAZRxlm1tpbNqughbDWI2h2bXweWbULPy6uXy0I=,tag:VCwvZA7Zo/IAyDAfqqpl5Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:LDog66tAbI3DYY6g,iv:xmD4vtxUZxnKoeeNryr9YSj8IqL/d1hnJomlHUxTo+M=,tag:bX4BQu3QOjKIm9Bs3B7Qhw==,type:str]
    #ENC[AES256_GCM,data:TUhNnlhhahcQvpnn1dVG4YN7z/9qRTX2GFnDxdYCJLtPTEsSXbMf02Yh6JqSHrk=,iv:8ctkRhiCw/hrizuoYY71dubd9+qXsj9TSjz3g0OQFCc=,tag:77eDzHOKyJX0uq5Kmxq1Ew==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:VPvXQDEefBDB+NQ+lZlJkGdgb4ER+nqoJ7ab,iv:hnW+8Iwe6a01xUTb3kTHhSvH+lOh6pfkaciyw5kZfkY=,tag:b12mzHRllkUQW57h+qNOHw==,type:str]
    #ENC[AES256_GCM,data:BvPMSmbOc8e0ICDBGKCESPIhSKJx77e/8+N8reJd8lB6fz1BftlPYdxmInAMOm6lWRO19tjkkx4kRCMWMoje+XLluR7oM3ZUHj0ZJ/5aSOM=,iv:QIuEd4BxKBOReejztLuMUGWVtVgpYUSAJYYOvlWWhXg=,tag:JXs4mT8dYTJzNTETnYjBwA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:/tc6FiT7rt+orXJO4A==,iv:Tyx9JH36DgW61C166KPnJ40JlESuKv+9/3gkL0O1n5o=,tag:PU935g56ATMG0gNIg+a5VA==,type:str]
    #ENC[AES256_GCM,data:PX29af/07ENEjyIAgS/qTHJr8VZbpVHp/cZyLTHGzFYO552/0A6XuFYpcizPrCVlBqOEzC1WKULKfFodXWILGlEDgHc=,iv:XVSR3yP77ucaNAZcB/azOSqKAD8Nj4rCrCPlB6xhE1g=,tag:jz+nbyiS5p9NoQMJD5YCSA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:R/FPr43DNYUcn3GvNg==,iv:jw8xo615yxWSgBvWCwBE3XRr62ATebU1rlPYA4TCg7g=,tag:p9u/jT0AXuru4Q5s7ReTfQ==,type:str]
    #ENC[AES256_GCM,data:MnvxuArktokoj9PfCmpPvRaU1ZLXbl6JFg1QbPQ7uAVtJQWVuTH9jHhV5kT/SFBXDbc6jS21JP4=,iv:LkAgL7WaSDvoh5jTULnDFBi2RobPjhCWFlCvkULdIkU=,tag:ihH8+vVyTZJxChugn3uXsw==,type:comment]
    #ENC[AES256_GCM,data://RIIFmBTf0cKvXlZn2xaXkCoo01NN8bcQ==,iv:BjbfBfVKPvvsjTJXsMOE9/0+7rZBwIU0UxRI5HLfVIg=,tag:Rq0Cj7aP8lowV1KYim8hXA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ppF8P0QDZdwnCXXV5XfUHmd1Mn6G3JVc2FWxuenBW+KHT9ZbX+EUTTYL8Q==,iv:2tKnMeJpkrfdBX3QcRRhGVK7kYflpA8ExSQ1fGDC640=,tag:Wz0ZI0bmIyZA4qzp0zpAbg==,type:str]
    #ENC[AES256_GCM,data:5Pd2XH78VacMoPpwLQ==,iv:h0Jm6dn10LF0Tpn/2QQp8g1AL4cuUPz3yocu6sPH90w=,tag:qA847XLig1YscxolJY8/rg==,type:comment]
    PODNET: ENC[AES256_GCM,data:7+yre3HjW7jop6NABA==,iv:CCPpZmEqmydP1nl3IeklAR4TPBgCrgflxIKUuA+PiQM=,tag:b4xTVQA/RQ+4dqWRh7Ha4Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:1fA5+X7YLf+KCrY0vw==,iv:nodhnEWNR4zZ4IV5XUeSJdGeHLTgS++uqhw/qCLIdPo=,tag:UsR+15hwsBStaXIdkKuWvg==,type:str]
    #ENC[AES256_GCM,data:Fs1MTnOv6H+iqA==,iv:9CkF/uSRZV2rtcx94CVpd8jrkUYLUSChRyTOTBTta+M=,tag:xW9ilzjtCmxCUMZ5njkoZA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:VdkeVg9G1EuKg99KoQ==,iv:FpX4+uw3fbSDM50qyu/NOiMyCBQ5eSjnaYAGbotpD+8=,tag:WQmqiHB87pIcbWSIcEFofg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:VE86UrK5blyOUnoScg==,iv:7ytwN7rLd1Hu+Q/FVzcJRshvQ2TfthOhUXcsPnTi3DE=,tag:nIryc9P0iboDPw1tHu2mtg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:UwDsc2P6Hp9hIOjqM4s=,iv:qXWFD9HqFJOnqeIVz/mjfs5jJNZRO0OKxo+f0QRdL3w=,tag:xdBwQT5OrqCoMGDKQK/Yvg==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:n5swy8FHM0FRXNTQpfY=,iv:D9GLe8XAdCIxh7JBhENGMeIqiaUHyWZLC4xgJl6u4rA=,tag:FmGR5RXHdycMvpny9TWr5Q==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:7/CJ3jNYl7E9hVaPYt8=,iv:4lKaEP6Pl+k7NN+RQLnk3T+rwPIBxm4xtdwPsaCfCo0=,tag:XpgyHcaFE5nOqDJIHhl5RA==,type:str]
    HA_IP: ENC[AES256_GCM,data:+2F4DgfPn6VQndAWtN4=,iv:9lhmECk8qfirtTDbqMuuOq8FK5N3JFU9DTA/Tul4GNw=,tag:dBoG/01uBapR7uuAteA89Q==,type:str]
    MC_IP: ENC[AES256_GCM,data:Bbgf9IztZrHdQj0qiK4=,iv:Y/chdv6ifgKrwmKgYtyjIkPiUwbvq8pj6o1v5ZkviFc=,tag:v3RP6D8Dcmoc9ghp34TFdQ==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:aiacr7Z4RorKxG0XKZ0=,iv:rWeRP6aUaiuKF0VLqPwtkIFK7jRXUEfihSjK3IMkJuc=,tag:9HTFmyGafIlbBeIueaDOAw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:SThz04dxAqnwfu3vRnldl9J8cyglDZtkMXK5w/I9FELJ0Y9+t6cRWQ==,iv:zcPVI3Ixb25aVEJ9LQJ5tmoRm5s6faQSmuk5gDuyKyk=,tag:Sg+SJoWWVy8Xce6curKzMA==,type:str]
    EMAIL: ENC[AES256_GCM,data:YboSGpaVLLAMlEuUXGnq/PBz5RUFsk4RfOFkCvKZ/g==,iv:iweYqSlhD1d1HOOZrOUz5a7E5Pq3Se+QQgLALkMsrLg=,tag:VxjVON9lyxbertLb3v2OVA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:cGi/kO/jko1ysj0SUQ==,iv:IEwA3UaxkJcOXXc3S96riGPrjLorHC/Ul8dUdmoc09g=,tag:46fdHhLrBk8UV1fP8o4zlQ==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:UFHR86LOjxZVXTBYu9AM+r/qeagb+HE=,iv:qVCYP2kKhexES+/zSyGfNR2soShJZNDFmUZ4YAoVxCU=,tag:lbgAd2r16MMh0sQ/nisWgQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:LKzspeIG0LyrC67den9ySjF/HpPYAUnhw9I=,iv:eXxI0yJrrc/564tWicutwwIJSel4rxttC1Ym1EskAm4=,tag:UqIjXW17efmXs/8qq26o8w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:WWZasQ==,iv:Vezyn8lUUz5JNot686eBniq0XfqnOfiiYCL02G3gneA=,tag:iRKO5HgJaLxOgl/17oSRnA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15r0fc8muy2t2wvyz7lxdrgk9us8jjnvs3evj7ju24zc6w7xavqas9q749m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeDBLcHFCNG9PZFJXR1hJ
            TWlGQVZWMHN3UFk4VVc3UXF0RDM1MVNxWjBzCjFoSnF5N1N3bWNOY283N3A5NGN3
            NVFBUEkwbUYrSnhpNmcyZlduZUdQR0kKLS0tIG9LeUhibHE1SUw1a0Q2bXI0bU5E
            MmF1bEhqS3UzZ3Y2MndYcmI5eThGM0UK8/soBGpC/FRpBIgQ/EMfcDBJAkGFP/Kl
            pjZR7/XX7fVi4yiNY1ju4Ki4MAdeLbg5bKYo/QJVJWUcGjKfOX6GIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T22:18:08Z"
    mac: ENC[AES256_GCM,data:f/yyjGzg1fQZCcYoZ7I4MnEummG12Sb83txId8nHuS7Pu3AJ8uZIbQRkxDs4G1RGWDSxheHd6VCPc/tahgAL7CH/y/BoSCiqfnxg+VNxZcMRvLHHUWBslRh+c8akDa+jDubHLxmbQTua7H6IqNPdOnq8dWBxp1VgDbVXYc1/0Ls=,iv:2XkwzFVib7P56I3zo8N2cT8VcQgEwhwDUjRXqFGrsCs=,tag:MWtlXQIWhIxaIUWZUOrN1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
