apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:28gVnkUky754hqsxRZMtgmGHgl+ZSlDO2wPJBlR1dvWdyLxg/gwFwCZJ5eRAOrQY6rGTprTB4Xaqvi3nuqggQdY=,iv:9kItzJ74r5+SrTBdCn6PJ13rqCNj1iIksd5REoUgKDw=,tag:VGHXG89IqWx5FBO6oFjGdw==,type:comment]
    #ENC[AES256_GCM,data:R7LqIWWWNmEUob4qOa5ALrgPy1673gXdCVwEw/p8tat85tlMP9TfmExjmZg=,iv:ea7skCvWxqldkALIO4p95RxPAOmFBs/CDV+TfteNvoE=,tag:ZBT40iiC6ThkZNQz1bGVIg==,type:comment]
    VIP: ENC[AES256_GCM,data:M1l3XyMQWNqDJlz2CQ==,iv:XbKRrYGSqKEWa3x7ouzlFzIDZvRPayDnvE6f2AuKWq4=,tag:x2Jp3641xQ74yHRTq8m9OQ==,type:str]
    #ENC[AES256_GCM,data:QbRAd0CL2mbG+ptjYRnqxcRTglKolQOSZRE=,iv:evKl7w0WeDEl6USVMEa5Wlp8mx84Yr6htoOZL2VvRUs=,tag:EFdtaRHYJ6ofdkveduF6lA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:id29V5EYYHvxqwvBycQ=,iv:3JvBbPf54v6akhWMU8I3+rA+FKwd9bE8MU1Ijx44QHY=,tag:E7IkuYcYTQ/hjX4W8vr5EQ==,type:str]
    #ENC[AES256_GCM,data:26lxYyfT/8dT4SzqV/wU6XNWdAs9X2FO5zmkdyCd0R5swQ==,iv:E3V0KFXrP2aDZ7AhVCPnLL64OfILpEptkZ6h68WhdUg=,tag:U28WhTbVOcKa/sYvaWzsaQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:RX4/SUZ0Q0+/vVuC,iv:0bKmYFi3jND3WuCuQv4ccZHuwc6yQgzWbz/B6VwldTA=,tag:k248lMLtH9uJNjGbOEW5UQ==,type:str]
    #ENC[AES256_GCM,data:uvwUuGqoKyep8XVBmx3DwdXAXsBX4VRRGfW4L/pHI2jAJMluvaT3WNyrkca9ejM=,iv:ChcjviQEez0n6yP5iDHhfRfyhi7AX9gYK73UBxnbsWU=,tag:fLI+hZCA3bdKTuKbhPvJfA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:WZAiSDfNW6vMkiMqA1gqRQe5wkezk7/njf0y,iv:LhTJnqVDVLowc01j7qm9l/GdHP4FAbtc2b9CUkQNSrY=,tag:5nqSlqeV+gMfjI8oqrLy/Q==,type:str]
    #ENC[AES256_GCM,data:9wzVO60/1DnarcCqrSzMh/Lkih9yMif6R4ouHuqom4UBEXevDNbP9NrSR2eLtpT1d8RYy4y+lX6CEjrNjtClMOnPOZk24HyzmXi3iBtzBi4=,iv:H1i0DCOB3j+nUfBmXxbgR8wAkhO+rVK4XCG4xmxQyYI=,tag:zNPaPyNHx/Du6i1Vl34HuQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:myuH3lLCtVguuBZiJg==,iv:wRLu57sZboxFluwYRY1u6oRyrUq5fcyWyGSMT6Dem1w=,tag:rJf1l136RkrQbEIc4qdr+Q==,type:str]
    #ENC[AES256_GCM,data:F85UuBlpEJz/ltrOrUpWEeAI/2XUc+o3jBQziHiLQ3SOaYDhpGcccnNhIawKmXOp0PbOHqxnDOxbYsowmYXYT0zmSGI=,iv:rAyzlswu6LxxLl8tIyUtjnNQ9vlfSkMhBl7SPv2gSt0=,tag:IVjRW0EMSewO92nB+ufh1w==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:v9ahfJXWm9li/J4T6g==,iv:iq5I2928nwmydWvFJeF0mtT6u+bBODwRUTqxQlX/dY4=,tag:IMNk2IohNFIuv9EGmLRw+g==,type:str]
    #ENC[AES256_GCM,data:OdB4nNfHN4XM4BPCxC6IPlvI53D3+Yyizc3v5DjJfSuyX3wzTHTubMxvQiZ2VBymV2aHTNnWXm8=,iv:u11oJRh4FrCy8QXlvnhwFMDTlXuTiFVOVl6b8cqnyUQ=,tag:Qcz3H1v7xLkqQ/D7+wsWgQ==,type:comment]
    #ENC[AES256_GCM,data:WqT/zScIwpBBa0jYNE94BkwXcy41KwshtA==,iv:qOz7hoblfhBf/qv03kECbQCpsYGhdJeZ9N+tMKVUNZk=,tag:m3F24HfrsA1iQBSXOn3lfA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:I+ecLG+c9xFGSiwINVadsH75FlaRWL+y1hW8sS2PTuwIybKelWbbF9SaTw==,iv:LO9iM+Nfgzi/L2YAoRKWuh25/PnW1Z4PYobaRuK2t5k=,tag:CyRqHo4v1Oc/wFEkyBIiNw==,type:str]
    #ENC[AES256_GCM,data:a93Lv4VR/1qrdXq1Pw==,iv:VE/jxUr4Iih80BRlRrNI5Np5PlZZgABP7eDds2vTXhk=,tag:sgxLGxLJifV/K2O//lDYLw==,type:comment]
    PODNET: ENC[AES256_GCM,data:keyl39rzmjzqNm6QqA==,iv:fqlLYaTaaYmTzkIfh8oxE3ZTRi4SV9/Mr6XMKSntZyM=,tag:cOjQhRQc91b9X2WBqHB2YA==,type:str]
    SVCNET: ENC[AES256_GCM,data:cTTKmyfQJTEpkTf8ew==,iv:oCDHYhINRgse3DRKOezCv+VgpjVKpVi++Vhvd6renCA=,tag:dTK0QZUv4ElMpculgDjAog==,type:str]
    #ENC[AES256_GCM,data:fKn2nvfvL3MzXQ==,iv:mGg52E850mUYqF2iA7I2DW8vqUFensBIcfEqigVN/b0=,tag:JFMSiGK7gFm3DWsx3K8n8A==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:F71kGk04I26cXOt8Lg==,iv:dluWzUKW9rHtvnTPnfe+n4G1pFNHgyUAFEvyCGGGa5Y=,tag:Y0IDyCTtRdDdttTs4XX7VQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:1y7zopJkMIhgo5DMWQ==,iv:IdHLteSOJSvTycNf2eZftJJHqE7SCwy8vjdF69rAO78=,tag:ei9QNZIj6DFZPyWpqIK2GA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:c0IR4ZvTC50BG2p1O5I=,iv:+YwccKLGE40DVHGKg/tis8rpfpR8u2b2mhoFLjhwl2k=,tag:T1MkAcpR7mYTiVbFWnZ1ww==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:FU8CNf9h4rslKPM3kKs=,iv:09O19BkGWMZGBi7k/pO3Aj0ObhZHFBP3Glwjto3caaM=,tag:SOcOaUfoN/ImT8R4R4osrw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:iw55wB34gR9mdrav2tE=,iv:pAEvyfYylUrRL1UmX4S8rpF7ib9Pj6DzPiT5+lzC0d8=,tag:MV0Um9BnGNWNzIA/whPmtg==,type:str]
    HA_IP: ENC[AES256_GCM,data:XOfrOXKelQKnxPQJjpE=,iv:36dIifLNRMju38aaoWaKwpy9TGDqlkRiSMNENH03dHo=,tag:Vcfm/wFEMxBMK037/t4woA==,type:str]
    MC_IP: ENC[AES256_GCM,data:pLlQUDhSKDCYz2QCAyg=,iv:xQTLUFKQT39BmroxLhKayx/Yf2ZIW95YHhvOcyaB2hE=,tag:p/R8H2NRj1Fq0ERPWuNi3g==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:W6m7cTYrnWx88tM1j5Y=,iv:rjX8eDJS+NimZAniArBdODiWriVIDJ20pg5wqNY9j+E=,tag:aUZvQD1+uikpjTsDgxoWaw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:DcqnjBOIfYlTkHsjB9xU7otgTfell/PWHreUUnx5yqalfq3zOUAk8w==,iv:JlAx/41xkS/nDKmz+dpbFJzPf3zONIkXUvrlmg9LGH8=,tag:LeBZCT7epHPv6MihiysqKQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:kvpVEzedhp2q4Nj7biq2kL7ufBs5M+cA1y31T+9DUQ==,iv:/XTXiofYF6fZMoZxkUADbb9VFjk+VBeuL/ttFSj66aU=,tag:F89+euNt7SqOulk3RcMdBQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:L5Kjb7ghtvph7Ei5Bg==,iv:tZ3Gf0mX03wUiiqHFOPd/rlaBOeTyiiL/Wb4B2LCWWo=,tag:ClUQt/g+WjtAZfBeDUM7rQ==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:hesmvlrglR3IAPhAYQKwB93+l1+4zu4=,iv:CJn65lc1Vz6kZq6D59f+dyJhXCC8v8lVgIJF3LXBoIc=,tag:5mC65nMzeDgnS1iCFgBfNQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:G4JQKmrZz7bJa3Fh+1Gi6I0GU5w0nvebRqI=,iv:T2JDg5FjO8vybhG0dbgPT91OwY2z8Ok0BtJw5CN4S10=,tag:3EDaTDRJV+lMd4h87oJ7FA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:DI9+Xg==,iv:gtup6tAk28ce59wGRufsMsVpKRyGc1Sa+9l550ALK+0=,tag:OZQnZHTCXhRkOM4gp2emAQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15r0fc8muy2t2wvyz7lxdrgk9us8jjnvs3evj7ju24zc6w7xavqas9q749m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZURBMzJMNGFaT2h3OHNT
            UktMKzE5MHV2UStJclFoNDRUdVA2M0ZIRjE4Cnd6SnBEZW13UXR5a0RTNjZhN1dH
            cUZuVFl1UFhiTUZkVGJOeVdUZFZOekkKLS0tIEJqbjN1d1h6dGljNFFLUGN1UTRa
            Vi9TRVNZSXJaOU14RzJiam1LcUR0TEkKAK9IKH1ghC/MxOD1S2e8tF9DRbuPZBKt
            zOM19rvLxs9pbmLrtHNgtrCddAWWkFQBLPjSDFgVAO6neklkjjuMkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T13:26:11Z"
    mac: ENC[AES256_GCM,data:ZvXJPuUzkw5AJ3x1GYqGIDAZ2sVcOV81+K1clkdnD36Hrke6lSD8VAZc9vJqoKkQPmPKSxytlqUE9QxlDfqfy9jLJbHG0XCsmbdt4/a3+4TNkWR7YkiEJfXhlyYj50Vk/AdHfU2WlkXlzDEDRJdGc8tSPteOkYufwcfWxf7FVqc=,iv:DzLrhtt/anYW0kNRtWA8zb7tf63jBNiPYs+OE5BJYCI=,tag:j6KmpO3qyVYeQxT1Y6I3Qg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
