apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:uil/HtGvq3HoE6CsvAfthoL/wrf2kjQqwapPQPFnTJXCcr/hK+PS2Z9R4fyrSN5sH+rI7NVmhoRRtF5AtYS88Eo=,iv:eqAnsIIX7ifGchJV93yFca2M8WnnO+nWM6iLJZTfEQY=,tag:hUi/8Sv3hvk6bfOZTSr8rA==,type:comment]
    #ENC[AES256_GCM,data:jVSCrXcoEU0OrH2AF/FuNW5UvJb4djAOPIisxtmDoVDZFmD8Eg0Ga08nW2M=,iv:NFgydFoV6soQgnf/lYKZVWeOt7PVxeGOiegLcmRYU+U=,tag:luUiQChKAy79E+b2/sw6KQ==,type:comment]
    VIP: ENC[AES256_GCM,data:ip7KcjHwuBxUAmDY9w==,iv:NO9RkPoBXlNchjPNO6rGGOdOvqNXDreWf2S+qhH806c=,tag:ywjQqG2fCCGfwc8EuDA1Ag==,type:str]
    #ENC[AES256_GCM,data:iqfscotepPwmuapdrbfpenxy1xF+n1N7rsE=,iv:jKSufBL1me1yez2nHOgmqIAeIfIBETN9UJKMeDPasJs=,tag:IUDMrkr1Mc7p1LduPErOqg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:P924ES5pK1G8Y3IraU4=,iv:ZrxyC4S4ezpltbbskN/Lrf9CiKNJ0GkNDCVh5dmZ6GA=,tag:exp6nF1Nt64PoyWt58CGnw==,type:str]
    #ENC[AES256_GCM,data:N3UolI7ctktt5loFpoOiIsrZ84KXXprVQltq5LPyL0AxiA==,iv:8+Y4ezKVZg0f463knk+40OwtuXniOy0U8+Nn9HvxBQs=,tag:aMwAtHiBmF2z16X38TdR/w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:TYIp12PwrgewzTWo,iv:t9IM3uGH6JBclNciFakqhdeFhMP+OqQG0kzIGYp7u0c=,tag:uvO4DDEgM7N/Mtf9yo87+g==,type:str]
    #ENC[AES256_GCM,data:NWbxAuBo6JKLZjueOtk25rPweF8PXRVHCoHIWTHzwhF1uvTWUbvOUyFTTzy6XEo=,iv:2qqzTrTUgEXU0NvRkblTMf4BWvhDDPjf2GJX7Fvp8Q0=,tag:sfaEWIPH5NC8gydG4zwmIg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:r9GW3gyQUcUyFrdsFxURgGiUXDEYWJGrtnJU,iv:qUSRZ1PbrFe5q28F+g0L3Jp1PS0n0CoHYeGTKlniSaE=,tag:lBWTgx9QvSPJyuUDdKTRkg==,type:str]
    #ENC[AES256_GCM,data:cX1SFkN+qAYfPQ+i4ngrbBre2sYqBxlFV2hvaW60y3C04zIhoKexWWIdl9Gxk5b8TpHwbGk/8xX5MldyKVt8BaOeZLKx5c4CuZz6sHVkDWw=,iv:azsg1t7MFjgQhYOF9xoj+Y7pT1YjXZAg+bOR6Nr08PA=,tag:OKGLHhlNEYxB5gbDdJ6MBw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:ZB6wXx+ndRw4sHcHuw==,iv:Pnzg6cZo5oq11k4pGInb8A54FgUlAowPNY7/IjyDHSE=,tag:q4zZNguYRn1XDmJa+eMHmQ==,type:str]
    #ENC[AES256_GCM,data:E7t8BHUYIg+2jRW0Fapl+BZy3f4C0el6N8LnGg8wYWLW02glbWkNgKaZypLHfI1yCZojummJV4B84et6zGD7VL/6ojE=,iv:MxZrMIp2x9M0I9qfTWhWGqZjS8cXXJwt9CcIjVpC9Os=,tag:WLjoeFE8A/HPtj11O+i7Mw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:TxRo+HeNVsJsHCMUFQ==,iv:oSUHwm1oI4chT0plz04BmygcZdaoYmeNI/IRnU0YDJE=,tag:yhDUntuVjP4nY7GJ9JcJvw==,type:str]
    #ENC[AES256_GCM,data:JjQXyyhfEaiiX2TqoiWRtrTOh+YdNUEJK+YR8V7CKiLKRDcOv938tKcEKWqfnj4kFp3o8fAi+i8=,iv:ujoedIun8YmMVIZ/98A/Mz+6NEamagqSQGmPhBc7EEs=,tag:jYS3qDvhc37cm6UJSp1XCA==,type:comment]
    #ENC[AES256_GCM,data:YiLrHYbr2kflgXDlKj4ZSljTUoGw++yBqQ==,iv:c4mJKP6CWiI8Vnl83shV32Nouuwgvtm47l4H0o2r16I=,tag:Duu0ddzFrILXFGOtln+2jg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:zkTJ3UV3Q7OJ92NIaE0uJ+CLStZhwExx12GZxXajWS5yOIzmWsnhe18RmQ==,iv:sM64wIjHPSspbvmvpS6PVeBNH4TR6DCEuReOud2wMBo=,tag:u11YN+wlKn4GnaqGU55JKQ==,type:str]
    #ENC[AES256_GCM,data:vc4bMJCvCOpYbsfLhg==,iv:spEk3rrWLLxJZEYT4b7NeqCCmaSiNUOdUcqFlog8e3I=,tag:rIN8qYn8vzoAGsSVhzvgDQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:JkVkm/FQ1ShRNhKXYQ==,iv:mWKhfAMJtAQBo5CiZ6wdbhCJ/KOSExDn72lp17oyHn0=,tag:GGzJaZB4PGNjHNtPmryonA==,type:str]
    SVCNET: ENC[AES256_GCM,data:rJwXr9yS5nE5JyLYZw==,iv:VT58B+GHNBS3v8fx3PsFRw5gptYC/IzIx1wMWA3y4SM=,tag:YdxIg6+01l2mYr8H0jb7JQ==,type:str]
    #ENC[AES256_GCM,data:p0zqstrXpB/qEg==,iv:oLxS2I782wQ6tZJYlmpai1vX/Rg8ap0vQb5v0DLuq1c=,tag:k8mZrxEjHQeRSlBKKM6FAA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:XjdAVdXbjJQ+FDTarw==,iv:LmUQKYqHhNzt1Zgo0XGQgA12DyLKGqRZh0AAL8FlM64=,tag:Qa6T4EUR0xA8MhL8cbNLvg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:tjjh8//aqq3tc6W1Rg==,iv:X+fKyqjOSIxKCmAAUiSy3J5FeUWDKcAflJJDL+Xx2M0=,tag:75InHyrsR0+42gTMXC3aYQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:SHFcM8hfCi3NLPawfZY=,iv:O2XCc1qg20dS0UrNAhom513Km5v01HFDRmBX1atXj80=,tag:CTZsnzQFnciY33qO0xCJ+g==,type:str]
    RADARR_IP: ENC[AES256_GCM,data:M+y9c9p+G0lDjpG51g==,iv:xSZArwsT0Pb3w5Ek+6cvRC0iiCVqAGrDBHglSmblvzY=,tag:TUSXQDDy/iFJ8gVH8qFP5Q==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:qkkPWZiQINOakTT8g5U=,iv:hblahXvyhdhul7X7qp/rGtLD+RfY+pSNRSDPPAn/1WI=,tag:liU/upjKniRUfX/l67CcXw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:niKgx2V2YI0b3W04dXc=,iv:lutIgnnlw9QniNRlMwDTcCADZH+1tm7pPflmHkkkKog=,tag:imSNueGQnb46raMI1mupuA==,type:str]
    HA_IP: ENC[AES256_GCM,data:o95rZieK0sQk4+GB+bM=,iv:VksH2y/L7ycqF6cpEqExl331oQwyO1mS4kT5Wtp3+Hs=,tag:VsUgRe6ILuAIjlz5xSxNXw==,type:str]
    MC_IP: ENC[AES256_GCM,data:7VheWA7l0rN0S/R6Huw=,iv:BNzKkNQ1ks9kzjTFNP/FEzmDLqlpwLYun0qC8rHLRPQ=,tag:bUOSPWumwM2dpGPEE1gp5A==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:J+fgnxx3o8chtFJZDcI=,iv:LwcDcxyscce04LWhZkz/iGHA4g0U4OfruuusU2+gGzs=,tag:j47wL3GMgZ64DFDG0KktVg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Gu5Gw6AnUPL350yvyIcyvRkXgG1OljRZzkFHNw5Gq3i2MM6OpnXXrA==,iv:ZtpLBarIBCKBm/bHHCQKygyU/BjvryX4kD5DDXfufJI=,tag:OP358pLm56oY1vUqiJh3QA==,type:str]
    EMAIL: ENC[AES256_GCM,data:0VhapuOYLV/0CnxNmZUdaxygwAr1T/MspdVfvxi9Jw==,iv:LRs1pDP5+7zqgZDLJCEh1Glgw+OBxTmVbL2nkdc6+hs=,tag:qhe7X/gSjbu716kxgOGxLQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:7NggzHBTNNXBPvs7pA==,iv:Jx1ygxry00jCtCregGRW59667qo3hTHFg3LQNXhX6gc=,tag:Er/tPnhTipN6EQ0EcoypUw==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:yu+/KjVxcQt00WHZPDv6d1a3W/2ibjc=,iv:WIix+Qz/TzgehiNY1nwCamIdvGiZBcvnmMMpAuJ8rPE=,tag:6bPYY4fGawRXLIb2I3DlmA==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:DGKfFcuJbBbDDnd/wlw0Fq9DTBhcGdSelz8=,iv:s8HHdTvMvr/Z69DQUAWH4A1LOjpb2F5QCdIx+IVAtDw=,tag:s+w8PuouJIfM+Xa9F6QLUg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:+U5+7g==,iv:E0weTcNvQmLuswaG9kNtfnfTi69p5elUWg791mQiuB4=,tag:nq/LfsVldmmapDNiy87oJQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15r0fc8muy2t2wvyz7lxdrgk9us8jjnvs3evj7ju24zc6w7xavqas9q749m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3FUVEpwMUQ4dWVHM2d5
            VGdSc3NUYWl1SE92VjJVRFlvYU5MUzgyVUcwCnpTTlZVTXZtR2Q2K00yalhDWFV0
            dkoySm1WaVpCREsxY08zd0xqOWZNRkkKLS0tIDNQLzhlaDZxaUp4bThoZzB2VTFO
            OFNGSE9GSVk1azZmL1pMYXlsVC81bVkKohvSXOR2hDhAP6A5X4uNCYJklZ+OUhNx
            g2yiscdmgRYHBR5Bhh/q3vrrzcqCh9oxPamvPcuSoiX3lHXPg+fGRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T21:41:22Z"
    mac: ENC[AES256_GCM,data:e7WKp5fZ8kG+FmR4A4YNf1Shs+fLS/ezXINl3I8yy0GF7h+z1mVgMTCf4SmTdhJUSmVZZ3blamvgPMF2kuxa9uLUxGB1Ymv9ShVIg5GQR6dRDYWhMgJnrmACDopCEXqrB/7LQp4zTK6RmvXxNpnmFYT1/A/gMRnBk6cUc/mRIvI=,iv:j+fCQQz67XCudqxmpVsgvBebY8vDaiT/r4b75ghUMx4=,tag:9D+hCCA2te3X5uzgxsTHtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
