apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oEKoVjDKgm39EHiYQV5Zg4cR2aLBYvweONDbtNsohYiHqatRlEJrM7EKOURKrB8Si8zYB6vXXsd41PKTBznrjq0IgfhCJEK/HNQACqGnKkuvdoJeyTt9e7SKOmGiktGj4ahkCHkjPP+gsZPRXwA9+4noHYsyQjt8Bs3B71HsLJqJYmot5+uMa7RZfQQ65M/wWkLMzudK1zzCZ+D0tJcovnc8hKzpC34Z/x0CqMTZrDx+OOPdz7xXUiznk/pdgwLRSggLKGgwMOxCG1K0kD3l1sJswOjs6zVZzueLcV3YThpAB+hik4BCs8H5aMUHrMW+SRZRpctfSWg0wsNVmH0Wz614zikZVRYqN2O6pQrNX3rtv0fwtfTb+UQl8Le+r6YH,iv:eQ9aWEBfhZOZrsE4xF+WxFyQyFmNX9Xljn1aB2ALDrA=,tag:779q9htfjT43B02LAKo1Dg==,type:str]
    identity.pub: ENC[AES256_GCM,data:/j2P2YcgBSJ7wKQ1S6JZECcL9J15JQFXC2JrPyi17J3lYWEO6M/0eetGwl0GEQUWB9DY/fliFovId8sqtwetDTbIVC3uIK4E66Cce1hZLMtbO5wMTVVDT3fLjDD3z+S10TMyWFIwKeJRbqk8FfZciHWoU/PqG8jrDFJK69SEYAQG61KIU6LSVlOhC322dwZLr3ZZvb4rqbno6/D/lqaqsvEmIyEsCXFpFrS2bhnO4eo3lSOx6ktaJqLjxXsxZm97PC43YB+IhBtipmQwNg==,iv:jlFQJm03BKy59MaXvSddNrf746Cp+6FK9XGOuEXwZFg=,tag:8c4xc7y7QFVN/Le/JRfw4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:zNTjTDmJeyX6sABfNH4FJqe6qr00e/jJ1KEKgLYfgos/uzureimywej5r0O6OuQAzZXODT/kfCNNpR9ywO7onzMULLcbi8ki23SWP5EqexGgq6cTDciCP3vT3qpsTDzb+tL04bnO2DXJCTyXolkBUCu0aiqQ09neTkRLWVAQ/HQMSCbPJj4wqWLD16v4WN3eoqZOmZFv7O0dhqmEUn8OKSAuRmNXcgi9svF3,iv:n9C0OOWxDa3qB4rMqXE8o4danBMCPVZNbTjGjL29TpY=,tag:F6ZAgDU70yHWr1KfCCv1Hw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15r0fc8muy2t2wvyz7lxdrgk9us8jjnvs3evj7ju24zc6w7xavqas9q749m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTDV5WHdUK1JHSjFyQmhv
            V1dVZkpaUlZPVjdKWEExZ3Rwb3d3UmhMMURvCnpzaTlTblRxZWJOcVBKQjRwY0pC
            dDVVLzY3L2dMdXQ1UkZtWFVBZHd5ZjAKLS0tIGpQUXR2QmlRaFg4b2xDSDkwRFV0
            TS9yWk9JZ0hWMkpCMGR5RjRTRk5POXcKiFU17WpX9+itCfjqHio1lkP1g3ONS5l+
            YoP1e8tRVyAmHXjd1eytoIMbw9il83C1/WsiCNO+SX9e3Ftt4dSatg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T21:44:05Z"
    mac: ENC[AES256_GCM,data:nktNVXBFGWkjnnxnH06oWB+lbgLUS36O+Kf6a1eObMnJSz643eSt/8R9OCrQ+lnAUJW/CfBDKt4rgo6tIGVJgeb5twzvAkcsVJKiIdmDkp4OCSukTRIXUPoZm4guiebp/51IY3d9E1S0bLj0Ot8Xp9M8QizmkyCBni+8sqnjlEs=,iv:u4z5XJizNpM11eKf8ZJh0bCA4CxWkgnUQMULGUzIVf4=,tag:RgJ+EZ0X+avfNoUO1aSxsw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
